version: "3"
services:
  web:
    build:
      context: ./www
      dockerfile: Dockerfile_web
    ports:
      - 80:80
    container_name: php80
    depends_on:
      - database
    volumes:
      - ./www:/var/www/html/
    networks:
      - my-network
  database:
    build:
      context: ./www
      dockerfile: Dockerfile_db
    container_name: mysql8
    image: mysql:8.2
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: rumama
      MYSQL_USER: ruben
      MYSQL_PASSWORD: ruben
    volumes:
       - ./init:/docker-entrypoint-initdb.d
    networks:
      - my-network
    ports:
      - 3306:3306
  miservico_phpmyadmin:
    build:
      context: ./www
      dockerfile: Dockerfile_phpmyadmin
    image: phpmyadmin/phpmyadmin
    ports:
     - 8080:80
    links: 
      - database
    networks:
      - my-network
networks:
  my-network:
   name: Red


